{{- if .Values.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-merger-bot
  labels:
    app: merger-bot
spec:
  selector:
    matchLabels:
      app: merger-bot
  template:
    metadata:
      labels:
        app: merger-bot
    spec:
      {{- include "buttercup.imagePullSecrets" . | nindent 6 }}
      initContainers:
      {{- include "buttercup.waitForRedis" . | nindent 6 }}
      containers:
      - name: merger-bot
        image: "{{ .Values.global.fuzzerImage.repository }}:{{ .Values.global.fuzzerImage.tag }}"
        imagePullPolicy: {{ .Values.global.fuzzerImage.pullPolicy }}
        command: ["buttercup-corpus-merger", "--crs_scratch_dir", "{{ include "buttercup.nodeLocalCrsScratchPath" . }}", "--redis_url", "{{ include "buttercup.core.redisUrl" . }}", "--timer", "{{ .Values.timer }}", "--timeout", "{{ .Values.timeout }}", "--crash_dir_count_limit", "{{ include "buttercup.core.crashDirCountLimit" . }}", "--max_local_files", "{{ .Values.max_local_files }}"]
        env: 
        {{- include "buttercup.env.nodeData" . | nindent 8 }}
        {{- include "buttercup.env.telemetry" . | nindent 8 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        {{- include "buttercup.standardVolumeMounts" (dict "usesTasksStorage" false) | nindent 8 }}
        {{- include "buttercup.nodeLocalVolumeMount" . | nindent 8 }}
      volumes:
      {{- include "buttercup.volumes.scratch" . | nindent 6 }}
      {{- include "buttercup.nodeLocalVolume" . | nindent 6 }}
{{- end }}
