apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scheduler
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      {{- include "buttercup.imagePullSecrets" . | nindent 6 }}
      enableServiceLinks: false
      volumes:
        {{- include "buttercup.volumes.scratch" . | nindent 8 }}
        {{- include "buttercup.volumes.tasks" . | nindent 8 }}
        {{- include "buttercup.nodeLocalVolume" . | nindent 8 }}
      initContainers:
      {{- include "buttercup.waitForRedis" . | nindent 6 }}
      containers:
      - name: scheduler
        image: "{{ .Values.global.orchestratorImage.repository }}:{{ .Values.global.orchestratorImage.tag }}"
        imagePullPolicy: {{ .Values.global.orchestratorImage.pullPolicy }}
        command: ["buttercup-scheduler", "serve"]
        env:
        {{- include "buttercup.commonEnv" . | nindent 8 }}
        {{- include "buttercup.schedulerEnv" . | nindent 8 }}
        - name: BUTTERCUP_SCHEDULER_SERVE__PATCH_REQUESTS_PER_VULNERABILITY
          value: "{{ .Values.patchRequestsPerVulnerability | default 1 }}"
        - name: BUTTERCUP_SCHEDULER_SERVE__CONCURRENT_PATCH_REQUESTS_PER_TASK
          value: "{{ .Values.concurrentPatchRequestsPerTask | default 6 }}"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          {{- include "buttercup.volumeMounts.scratch" . | nindent 10 }}
          {{- include "buttercup.volumeMounts.tasks" . | nindent 10 }}
          {{- include "buttercup.nodeLocalVolumeMount" . | nindent 10 }}