apiVersion: v2
name: buttercup
description: A minimal Redis deployment
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
  - name: dind-daemon
    version: "*"
    repository: "file://charts/dind-daemon"
  - name: litellm-helm
    version: "0.1.615"
    repository: "oci://ghcr.io/berriai"
  - name: task-server
    version: "0.0.1"
    repository: "file://charts/task-server"
  - name: task-downloader
    version: "0.0.1"
    repository: "file://charts/task-downloader"
  - name: scheduler
    version: "0.0.1"
    repository: "file://charts/scheduler"
  - name: program-model
    version: "0.0.1"
    repository: "file://charts/program-model"
  - name: build-bot
    version: "0.0.1"
    repository: "file://charts/build-bot"
  - name: fuzzer-bot
    version: "0.0.1"
    repository: "file://charts/fuzzer-bot"
  - name: coverage-bot
    version: "0.0.1"
    repository: "file://charts/coverage-bot"
  - name: tracer-bot
    version: "0.0.1"
    repository: "file://charts/tracer-bot"
  - name: seed-gen
    version: "0.0.1"
    repository: "file://charts/seed-gen"
  - name: patcher
    version: "0.0.1"
    repository: "file://charts/patcher"
  - name: competition-api
    version: "0.0.1"
    repository: "file://charts/competition-api"
  - name: registry-cache
    version: "0.1.0"
    repository: "file://charts/registry-cache"
  - name: pov-reproducer
    version: "*"
    repository: "file://charts/pov-reproducer"
  - name: scratch-cleaner
    version: "0.0.1"
    repository: "file://charts/scratch-cleaner"
