{{- if .Values.global.langfuse.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-langfuse-secrets
  labels:
    app.kubernetes.io/name: langfuse-secrets
type: Opaque
data:
  # Secret values to be filled by the user
  # The values need to be base64 encoded
  LANGFUSE_HOST: {{ .Values.global.langfuse.host | b64enc | quote }}
  LANGFUSE_PUBLIC_KEY: {{ .Values.global.langfuse.publicKey | b64enc | quote }}
  LANGFUSE_SECRET_KEY: {{ .Values.global.langfuse.secretKey | b64enc | quote }}
{{- end }}