{{- if .Values.litellm }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-litellm-api-secrets
  labels:
    app.kubernetes.io/name: litellm-api-secrets
type: Opaque
data:
  # Secret values to be filled by the user
  # The values need to be base64 encoded
  AZURE_API_BASE: {{ .Values.litellm.azure.apiBase | b64enc | quote }}
  AZURE_API_KEY: {{ .Values.litellm.azure.apiKey | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.litellm.openai.apiKey | b64enc | quote }}
  ANTHROPIC_API_KEY: {{ .Values.litellm.anthropic.apiKey | b64enc | quote }}
  BUTTERCUP_LITELLM_KEY: {{ .Values.litellm.masterKey | b64enc | quote }}
{{- end }}
