apiVersion: v2
name: pov-reproducer
description: A Helm chart for POV Reproducer service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - pov
  - reproducer
  - orchestrator
maintainers:
  - name: Trail of Bits 